name: magicspell
main: com.pilzo.magicspell.MagicSpell
version: 0.0.1
api-version: 1.15
permissions:
  magicspell.cast.jail:
    description: Cast a jail
    default: op
  magicspell.cast.longjump:
    description: Get a long jump
    default: op
  magicspell.cast.heal:
    description: Heal yourself
    default: op